// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: polybuf.proto

package polybuf.core.proto;

public final class Polybuf {
  private Polybuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(polybuf.core.proto.Polybuf.file);
    registry.add(polybuf.core.proto.Polybuf.message);
  }
  public interface FileOptionsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string namespace_uri = 1;
    boolean hasNamespaceUri();
    String getNamespaceUri();
  }
  public static final class FileOptions extends
      com.google.protobuf.GeneratedMessage
      implements FileOptionsOrBuilder {
    // Use FileOptions.newBuilder() to construct.
    private FileOptions(Builder builder) {
      super(builder);
    }
    private FileOptions(boolean noInit) {}
    
    private static final FileOptions defaultInstance;
    public static FileOptions getDefaultInstance() {
      return defaultInstance;
    }
    
    public FileOptions getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return polybuf.core.proto.Polybuf.internal_static_polybuf_FileOptions_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return polybuf.core.proto.Polybuf.internal_static_polybuf_FileOptions_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string namespace_uri = 1;
    public static final int NAMESPACE_URI_FIELD_NUMBER = 1;
    private java.lang.Object namespaceUri_;
    public boolean hasNamespaceUri() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getNamespaceUri() {
      java.lang.Object ref = namespaceUri_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          namespaceUri_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNamespaceUriBytes() {
      java.lang.Object ref = namespaceUri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        namespaceUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      namespaceUri_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNamespaceUri()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNamespaceUriBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNamespaceUriBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static polybuf.core.proto.Polybuf.FileOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static polybuf.core.proto.Polybuf.FileOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static polybuf.core.proto.Polybuf.FileOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static polybuf.core.proto.Polybuf.FileOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static polybuf.core.proto.Polybuf.FileOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static polybuf.core.proto.Polybuf.FileOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static polybuf.core.proto.Polybuf.FileOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static polybuf.core.proto.Polybuf.FileOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static polybuf.core.proto.Polybuf.FileOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static polybuf.core.proto.Polybuf.FileOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(polybuf.core.proto.Polybuf.FileOptions prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements polybuf.core.proto.Polybuf.FileOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return polybuf.core.proto.Polybuf.internal_static_polybuf_FileOptions_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return polybuf.core.proto.Polybuf.internal_static_polybuf_FileOptions_fieldAccessorTable;
      }
      
      // Construct using polybuf.core.proto.Polybuf.FileOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        namespaceUri_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return polybuf.core.proto.Polybuf.FileOptions.getDescriptor();
      }
      
      public polybuf.core.proto.Polybuf.FileOptions getDefaultInstanceForType() {
        return polybuf.core.proto.Polybuf.FileOptions.getDefaultInstance();
      }
      
      public polybuf.core.proto.Polybuf.FileOptions build() {
        polybuf.core.proto.Polybuf.FileOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private polybuf.core.proto.Polybuf.FileOptions buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        polybuf.core.proto.Polybuf.FileOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public polybuf.core.proto.Polybuf.FileOptions buildPartial() {
        polybuf.core.proto.Polybuf.FileOptions result = new polybuf.core.proto.Polybuf.FileOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.namespaceUri_ = namespaceUri_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof polybuf.core.proto.Polybuf.FileOptions) {
          return mergeFrom((polybuf.core.proto.Polybuf.FileOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(polybuf.core.proto.Polybuf.FileOptions other) {
        if (other == polybuf.core.proto.Polybuf.FileOptions.getDefaultInstance()) return this;
        if (other.hasNamespaceUri()) {
          setNamespaceUri(other.getNamespaceUri());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNamespaceUri()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              namespaceUri_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string namespace_uri = 1;
      private java.lang.Object namespaceUri_ = "";
      public boolean hasNamespaceUri() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getNamespaceUri() {
        java.lang.Object ref = namespaceUri_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          namespaceUri_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNamespaceUri(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        namespaceUri_ = value;
        onChanged();
        return this;
      }
      public Builder clearNamespaceUri() {
        bitField0_ = (bitField0_ & ~0x00000001);
        namespaceUri_ = getDefaultInstance().getNamespaceUri();
        onChanged();
        return this;
      }
      void setNamespaceUri(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        namespaceUri_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:polybuf.FileOptions)
    }
    
    static {
      defaultInstance = new FileOptions(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:polybuf.FileOptions)
  }
  
  public interface MessageOptionsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bool rootable = 1 [default = false];
    boolean hasRootable();
    boolean getRootable();
  }
  public static final class MessageOptions extends
      com.google.protobuf.GeneratedMessage
      implements MessageOptionsOrBuilder {
    // Use MessageOptions.newBuilder() to construct.
    private MessageOptions(Builder builder) {
      super(builder);
    }
    private MessageOptions(boolean noInit) {}
    
    private static final MessageOptions defaultInstance;
    public static MessageOptions getDefaultInstance() {
      return defaultInstance;
    }
    
    public MessageOptions getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return polybuf.core.proto.Polybuf.internal_static_polybuf_MessageOptions_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return polybuf.core.proto.Polybuf.internal_static_polybuf_MessageOptions_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional bool rootable = 1 [default = false];
    public static final int ROOTABLE_FIELD_NUMBER = 1;
    private boolean rootable_;
    public boolean hasRootable() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getRootable() {
      return rootable_;
    }
    
    private void initFields() {
      rootable_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, rootable_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, rootable_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static polybuf.core.proto.Polybuf.MessageOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static polybuf.core.proto.Polybuf.MessageOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static polybuf.core.proto.Polybuf.MessageOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static polybuf.core.proto.Polybuf.MessageOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static polybuf.core.proto.Polybuf.MessageOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static polybuf.core.proto.Polybuf.MessageOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static polybuf.core.proto.Polybuf.MessageOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static polybuf.core.proto.Polybuf.MessageOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static polybuf.core.proto.Polybuf.MessageOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static polybuf.core.proto.Polybuf.MessageOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(polybuf.core.proto.Polybuf.MessageOptions prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements polybuf.core.proto.Polybuf.MessageOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return polybuf.core.proto.Polybuf.internal_static_polybuf_MessageOptions_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return polybuf.core.proto.Polybuf.internal_static_polybuf_MessageOptions_fieldAccessorTable;
      }
      
      // Construct using polybuf.core.proto.Polybuf.MessageOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        rootable_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return polybuf.core.proto.Polybuf.MessageOptions.getDescriptor();
      }
      
      public polybuf.core.proto.Polybuf.MessageOptions getDefaultInstanceForType() {
        return polybuf.core.proto.Polybuf.MessageOptions.getDefaultInstance();
      }
      
      public polybuf.core.proto.Polybuf.MessageOptions build() {
        polybuf.core.proto.Polybuf.MessageOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private polybuf.core.proto.Polybuf.MessageOptions buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        polybuf.core.proto.Polybuf.MessageOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public polybuf.core.proto.Polybuf.MessageOptions buildPartial() {
        polybuf.core.proto.Polybuf.MessageOptions result = new polybuf.core.proto.Polybuf.MessageOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rootable_ = rootable_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof polybuf.core.proto.Polybuf.MessageOptions) {
          return mergeFrom((polybuf.core.proto.Polybuf.MessageOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(polybuf.core.proto.Polybuf.MessageOptions other) {
        if (other == polybuf.core.proto.Polybuf.MessageOptions.getDefaultInstance()) return this;
        if (other.hasRootable()) {
          setRootable(other.getRootable());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rootable_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bool rootable = 1 [default = false];
      private boolean rootable_ ;
      public boolean hasRootable() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getRootable() {
        return rootable_;
      }
      public Builder setRootable(boolean value) {
        bitField0_ |= 0x00000001;
        rootable_ = value;
        onChanged();
        return this;
      }
      public Builder clearRootable() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rootable_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:polybuf.MessageOptions)
    }
    
    static {
      defaultInstance = new MessageOptions(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:polybuf.MessageOptions)
  }
  
  public static final int FILE_FIELD_NUMBER = 67890;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      polybuf.core.proto.Polybuf.FileOptions> file = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        polybuf.core.proto.Polybuf.FileOptions.class,
        polybuf.core.proto.Polybuf.FileOptions.getDefaultInstance());
  public static final int MESSAGE_FIELD_NUMBER = 67890;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      polybuf.core.proto.Polybuf.MessageOptions> message = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        polybuf.core.proto.Polybuf.MessageOptions.class,
        polybuf.core.proto.Polybuf.MessageOptions.getDefaultInstance());
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_polybuf_FileOptions_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_polybuf_FileOptions_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_polybuf_MessageOptions_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_polybuf_MessageOptions_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpolybuf.proto\022\007polybuf\032 google/protobu" +
      "f/descriptor.proto\"$\n\013FileOptions\022\025\n\rnam" +
      "espace_uri\030\001 \002(\t\")\n\016MessageOptions\022\027\n\010ro" +
      "otable\030\001 \001(\010:\005false:B\n\004file\022\034.google.pro" +
      "tobuf.FileOptions\030\262\222\004 \001(\0132\024.polybuf.File" +
      "Options:K\n\007message\022\037.google.protobuf.Mes" +
      "sageOptions\030\262\222\004 \001(\0132\027.polybuf.MessageOpt" +
      "ionsB\024\n\022polybuf.core.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_polybuf_FileOptions_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_polybuf_FileOptions_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_polybuf_FileOptions_descriptor,
              new java.lang.String[] { "NamespaceUri", },
              polybuf.core.proto.Polybuf.FileOptions.class,
              polybuf.core.proto.Polybuf.FileOptions.Builder.class);
          internal_static_polybuf_MessageOptions_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_polybuf_MessageOptions_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_polybuf_MessageOptions_descriptor,
              new java.lang.String[] { "Rootable", },
              polybuf.core.proto.Polybuf.MessageOptions.class,
              polybuf.core.proto.Polybuf.MessageOptions.Builder.class);
          file.internalInit(descriptor.getExtensions().get(0));
          message.internalInit(descriptor.getExtensions().get(1));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
