// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extensions_ext_same_package.proto

package polybuf.core.test;

public final class ExtensionsExtSamePackage {
  private ExtensionsExtSamePackage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(polybuf.core.test.ExtensionsExtSamePackage.Scope.id);
  }
  public interface ScopeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  public static final class Scope extends
      com.google.protobuf.GeneratedMessage
      implements ScopeOrBuilder {
    // Use Scope.newBuilder() to construct.
    private Scope(Builder builder) {
      super(builder);
    }
    private Scope(boolean noInit) {}
    
    private static final Scope defaultInstance;
    public static Scope getDefaultInstance() {
      return defaultInstance;
    }
    
    public Scope getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return polybuf.core.test.ExtensionsExtSamePackage.internal_static_base_Scope_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return polybuf.core.test.ExtensionsExtSamePackage.internal_static_base_Scope_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static polybuf.core.test.ExtensionsExtSamePackage.Scope parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static polybuf.core.test.ExtensionsExtSamePackage.Scope parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static polybuf.core.test.ExtensionsExtSamePackage.Scope parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static polybuf.core.test.ExtensionsExtSamePackage.Scope parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static polybuf.core.test.ExtensionsExtSamePackage.Scope parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static polybuf.core.test.ExtensionsExtSamePackage.Scope parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static polybuf.core.test.ExtensionsExtSamePackage.Scope parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static polybuf.core.test.ExtensionsExtSamePackage.Scope parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static polybuf.core.test.ExtensionsExtSamePackage.Scope parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static polybuf.core.test.ExtensionsExtSamePackage.Scope parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(polybuf.core.test.ExtensionsExtSamePackage.Scope prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements polybuf.core.test.ExtensionsExtSamePackage.ScopeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return polybuf.core.test.ExtensionsExtSamePackage.internal_static_base_Scope_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return polybuf.core.test.ExtensionsExtSamePackage.internal_static_base_Scope_fieldAccessorTable;
      }
      
      // Construct using polybuf.core.test.ExtensionsExtSamePackage.Scope.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return polybuf.core.test.ExtensionsExtSamePackage.Scope.getDescriptor();
      }
      
      public polybuf.core.test.ExtensionsExtSamePackage.Scope getDefaultInstanceForType() {
        return polybuf.core.test.ExtensionsExtSamePackage.Scope.getDefaultInstance();
      }
      
      public polybuf.core.test.ExtensionsExtSamePackage.Scope build() {
        polybuf.core.test.ExtensionsExtSamePackage.Scope result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private polybuf.core.test.ExtensionsExtSamePackage.Scope buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        polybuf.core.test.ExtensionsExtSamePackage.Scope result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public polybuf.core.test.ExtensionsExtSamePackage.Scope buildPartial() {
        polybuf.core.test.ExtensionsExtSamePackage.Scope result = new polybuf.core.test.ExtensionsExtSamePackage.Scope(this);
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof polybuf.core.test.ExtensionsExtSamePackage.Scope) {
          return mergeFrom((polybuf.core.test.ExtensionsExtSamePackage.Scope)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(polybuf.core.test.ExtensionsExtSamePackage.Scope other) {
        if (other == polybuf.core.test.ExtensionsExtSamePackage.Scope.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:base.Scope)
    }
    
    static {
      defaultInstance = new Scope(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:base.Scope)
    public static final int ID_FIELD_NUMBER = 100;
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        polybuf.core.test.ExtensionsBase.Message1,
        java.lang.Integer> id = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          polybuf.core.test.ExtensionsExtSamePackage.Scope.getDefaultInstance(),
          0,
          java.lang.Integer.class,
          null);
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_base_Scope_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_base_Scope_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!extensions_ext_same_package.proto\022\004bas" +
      "e\032\rpolybuf.proto\032\025extensions_base.proto\"" +
      "#\n\005Scope2\032\n\002id\022\016.base.Message1\030d \002(\005BX\n\021" +
      "polybuf.core.test\222\223!A\n?http://www.exampl" +
      "e.org/polybuf-test/extensions/ext_same_p" +
      "ackage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_base_Scope_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_base_Scope_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_base_Scope_descriptor,
              new java.lang.String[] { },
              polybuf.core.test.ExtensionsExtSamePackage.Scope.class,
              polybuf.core.test.ExtensionsExtSamePackage.Scope.Builder.class);
          com.google.protobuf.ExtensionRegistry registry =
            com.google.protobuf.ExtensionRegistry.newInstance();
          registerAllExtensions(registry);
          polybuf.core.proto.Polybuf.registerAllExtensions(registry);
          polybuf.core.test.ExtensionsBase.registerAllExtensions(registry);
          return registry;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          polybuf.core.proto.Polybuf.getDescriptor(),
          polybuf.core.test.ExtensionsBase.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
