// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extensions_ext.proto

package polybuf.core.test;

public final class ExtensionsExt {
  private ExtensionsExt() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(polybuf.core.test.ExtensionsExt.id);
    registry.add(polybuf.core.test.ExtensionsExt.type);
    registry.add(polybuf.core.test.ExtensionsExt.baseType);
    registry.add(polybuf.core.test.ExtensionsExt.Scope.type);
  }
  public enum Enum1
      implements com.google.protobuf.ProtocolMessageEnum {
    X(0, 0),
    Y(1, 1),
    Z(2, 2),
    ;
    
    public static final int X_VALUE = 0;
    public static final int Y_VALUE = 1;
    public static final int Z_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static Enum1 valueOf(int value) {
      switch (value) {
        case 0: return X;
        case 1: return Y;
        case 2: return Z;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Enum1>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Enum1>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Enum1>() {
            public Enum1 findValueByNumber(int number) {
              return Enum1.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return polybuf.core.test.ExtensionsExt.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final Enum1[] VALUES = {
      X, Y, Z, 
    };
    
    public static Enum1 valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private Enum1(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:ext.Enum1)
  }
  
  public interface ScopeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  public static final class Scope extends
      com.google.protobuf.GeneratedMessage
      implements ScopeOrBuilder {
    // Use Scope.newBuilder() to construct.
    private Scope(Builder builder) {
      super(builder);
    }
    private Scope(boolean noInit) {}
    
    private static final Scope defaultInstance;
    public static Scope getDefaultInstance() {
      return defaultInstance;
    }
    
    public Scope getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return polybuf.core.test.ExtensionsExt.internal_static_ext_Scope_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return polybuf.core.test.ExtensionsExt.internal_static_ext_Scope_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static polybuf.core.test.ExtensionsExt.Scope parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static polybuf.core.test.ExtensionsExt.Scope parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static polybuf.core.test.ExtensionsExt.Scope parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static polybuf.core.test.ExtensionsExt.Scope parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static polybuf.core.test.ExtensionsExt.Scope parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static polybuf.core.test.ExtensionsExt.Scope parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static polybuf.core.test.ExtensionsExt.Scope parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static polybuf.core.test.ExtensionsExt.Scope parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static polybuf.core.test.ExtensionsExt.Scope parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static polybuf.core.test.ExtensionsExt.Scope parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(polybuf.core.test.ExtensionsExt.Scope prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements polybuf.core.test.ExtensionsExt.ScopeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return polybuf.core.test.ExtensionsExt.internal_static_ext_Scope_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return polybuf.core.test.ExtensionsExt.internal_static_ext_Scope_fieldAccessorTable;
      }
      
      // Construct using polybuf.core.test.ExtensionsExt.Scope.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return polybuf.core.test.ExtensionsExt.Scope.getDescriptor();
      }
      
      public polybuf.core.test.ExtensionsExt.Scope getDefaultInstanceForType() {
        return polybuf.core.test.ExtensionsExt.Scope.getDefaultInstance();
      }
      
      public polybuf.core.test.ExtensionsExt.Scope build() {
        polybuf.core.test.ExtensionsExt.Scope result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private polybuf.core.test.ExtensionsExt.Scope buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        polybuf.core.test.ExtensionsExt.Scope result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public polybuf.core.test.ExtensionsExt.Scope buildPartial() {
        polybuf.core.test.ExtensionsExt.Scope result = new polybuf.core.test.ExtensionsExt.Scope(this);
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof polybuf.core.test.ExtensionsExt.Scope) {
          return mergeFrom((polybuf.core.test.ExtensionsExt.Scope)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(polybuf.core.test.ExtensionsExt.Scope other) {
        if (other == polybuf.core.test.ExtensionsExt.Scope.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:ext.Scope)
    }
    
    static {
      defaultInstance = new Scope(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ext.Scope)
    public static final int TYPE_FIELD_NUMBER = 100;
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        polybuf.core.test.ExtensionsBase.Message2,
        polybuf.core.test.ExtensionsExt.Enum1> type = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          polybuf.core.test.ExtensionsExt.Scope.getDefaultInstance(),
          0,
          polybuf.core.test.ExtensionsExt.Enum1.class,
          null);
  }
  
  public interface Message1OrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
  }
  public static final class Message1 extends
      com.google.protobuf.GeneratedMessage
      implements Message1OrBuilder {
    // Use Message1.newBuilder() to construct.
    private Message1(Builder builder) {
      super(builder);
    }
    private Message1(boolean noInit) {}
    
    private static final Message1 defaultInstance;
    public static Message1 getDefaultInstance() {
      return defaultInstance;
    }
    
    public Message1 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return polybuf.core.test.ExtensionsExt.internal_static_ext_Message1_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return polybuf.core.test.ExtensionsExt.internal_static_ext_Message1_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static polybuf.core.test.ExtensionsExt.Message1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static polybuf.core.test.ExtensionsExt.Message1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static polybuf.core.test.ExtensionsExt.Message1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static polybuf.core.test.ExtensionsExt.Message1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static polybuf.core.test.ExtensionsExt.Message1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static polybuf.core.test.ExtensionsExt.Message1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static polybuf.core.test.ExtensionsExt.Message1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static polybuf.core.test.ExtensionsExt.Message1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static polybuf.core.test.ExtensionsExt.Message1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static polybuf.core.test.ExtensionsExt.Message1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(polybuf.core.test.ExtensionsExt.Message1 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements polybuf.core.test.ExtensionsExt.Message1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return polybuf.core.test.ExtensionsExt.internal_static_ext_Message1_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return polybuf.core.test.ExtensionsExt.internal_static_ext_Message1_fieldAccessorTable;
      }
      
      // Construct using polybuf.core.test.ExtensionsExt.Message1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return polybuf.core.test.ExtensionsExt.Message1.getDescriptor();
      }
      
      public polybuf.core.test.ExtensionsExt.Message1 getDefaultInstanceForType() {
        return polybuf.core.test.ExtensionsExt.Message1.getDefaultInstance();
      }
      
      public polybuf.core.test.ExtensionsExt.Message1 build() {
        polybuf.core.test.ExtensionsExt.Message1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private polybuf.core.test.ExtensionsExt.Message1 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        polybuf.core.test.ExtensionsExt.Message1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public polybuf.core.test.ExtensionsExt.Message1 buildPartial() {
        polybuf.core.test.ExtensionsExt.Message1 result = new polybuf.core.test.ExtensionsExt.Message1(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof polybuf.core.test.ExtensionsExt.Message1) {
          return mergeFrom((polybuf.core.test.ExtensionsExt.Message1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(polybuf.core.test.ExtensionsExt.Message1 other) {
        if (other == polybuf.core.test.ExtensionsExt.Message1.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:ext.Message1)
    }
    
    static {
      defaultInstance = new Message1(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ext.Message1)
  }
  
  public static final int ID_FIELD_NUMBER = 100;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      polybuf.core.test.ExtensionsBase.Message1,
      java.lang.Integer> id = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int TYPE_FIELD_NUMBER = 101;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      polybuf.core.test.ExtensionsBase.Message1,
      polybuf.core.test.ExtensionsExt.Enum1> type = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        polybuf.core.test.ExtensionsExt.Enum1.class,
        null);
  public static final int BASE_TYPE_FIELD_NUMBER = 102;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      polybuf.core.test.ExtensionsBase.Message1,
      polybuf.core.test.ExtensionsBase.Enum1> baseType = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        polybuf.core.test.ExtensionsBase.Enum1.class,
        null);
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ext_Scope_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ext_Scope_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ext_Message1_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ext_Message1_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024extensions_ext.proto\022\003ext\032\rpolybuf.pro" +
      "to\032\025extensions_base.proto\"1\n\005Scope2(\n\004ty" +
      "pe\022\016.base.Message2\030d \002(\0162\n.ext.Enum1\"\036\n\010" +
      "Message1\022\n\n\002id\030\001 \002(\t:\006\222\223!\002\010\001*\034\n\005Enum1\022\005\n" +
      "\001X\020\000\022\005\n\001Y\020\001\022\005\n\001Z\020\002:\032\n\002id\022\016.base.Message1" +
      "\030d \002(\005:(\n\004type\022\016.base.Message1\030e \001(\0162\n.e" +
      "xt.Enum1:.\n\tbase_type\022\016.base.Message1\030f " +
      "\001(\0162\013.base.Enum1BK\n\021polybuf.core.test\222\223!" +
      "4\n2http://www.example.org/polybuf-test/e" +
      "xtensions/ext"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ext_Scope_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ext_Scope_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ext_Scope_descriptor,
              new java.lang.String[] { },
              polybuf.core.test.ExtensionsExt.Scope.class,
              polybuf.core.test.ExtensionsExt.Scope.Builder.class);
          internal_static_ext_Message1_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ext_Message1_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ext_Message1_descriptor,
              new java.lang.String[] { "Id", },
              polybuf.core.test.ExtensionsExt.Message1.class,
              polybuf.core.test.ExtensionsExt.Message1.Builder.class);
          id.internalInit(descriptor.getExtensions().get(0));
          type.internalInit(descriptor.getExtensions().get(1));
          baseType.internalInit(descriptor.getExtensions().get(2));
          com.google.protobuf.ExtensionRegistry registry =
            com.google.protobuf.ExtensionRegistry.newInstance();
          registerAllExtensions(registry);
          polybuf.core.proto.Polybuf.registerAllExtensions(registry);
          polybuf.core.test.ExtensionsBase.registerAllExtensions(registry);
          return registry;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          polybuf.core.proto.Polybuf.getDescriptor(),
          polybuf.core.test.ExtensionsBase.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
